### ISSUE TITLE
Failed to install plugin

### ISSUE THREAD

**Issue by cheesecakeassassin** [pokedotdev/tokyo-night-insomnia#3]
I keep getting this error whenever I try to install it:
`Error invoking remote method 'installPlugin': Error: Yarn error warning package.json: No license field
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. 
To clear this warning, remove package-lock.json.
warning No license field
warning No license field`

**Comment by pokedotdev** [comment]
Hi, I experienced the same error, but when I reloaded the plugins I was able to install it. It seems to be an Insomnia bug, but if it's not, and it only happens to you with the Tokyo Night theme, please let me know

![Screen Shot 2022-04-10 at 20 11 07](https://user-images.githubusercontent.com/40857565/162659501-af63c327-317f-4830-b599-f5b734814408.png)

**Comment by cheesecakeassassin** [comment]
Thank you Arturo, I will try this as well as attempt with other plugins and let you know

**Comment by cheesecakeassassin** [comment]
No plugins are installing for me, I'm gonna assume that it is Insomnia's fault. Muchas gracias Arturo
