### ISSUE TITLE
Bad looking HTTP method badges in new versions of Insomnia

### ISSUE THREAD

**Issue by SylvanasCry** [pokedotdev/tokyo-night-insomnia#4]
### Summary

HTTP method badges in new versions of Insomnia look a little hard to read.

Insomnia v2023.5.8 or earlier:

<img width="205" alt="v2023.5.8" src="https://github.com/pokedotdev/tokyo-night-insomnia/assets/140824195/57bd18ff-41ac-4689-9aa5-dcfccb43e9d3">

Insomnia 8.6.1 (current, at the time of writing issue):

<img width="205" alt="v8.6.1" src="https://github.com/pokedotdev/tokyo-night-insomnia/assets/140824195/2589cd5b-2c79-44a2-8e80-8bc09eb19141">

### Suggestion

Dark letters on a dark background are difficult to read. Is it possible to make them lighter so that there is a distinct contrast?

**Comment by satokenta940** [comment]
I also think so, but I have switched to [Apidog ](https://apidog.com/)so far, and I think its UI really suits my taste.

**Comment by SylvanasCry** [comment]
> I also think so, but I have switched to [Apidog ](https://apidog.com/)so far, and I think its UI really suits my taste.

Sounds like an ad :)

**Comment by pokedotdev** [comment]
Thanks for the report @SylvanasCry! 😁 

I didn't like how it looked with the opaque backgrounds, so I overwrote the styles to achieve the old style.

Available in the latest version.
![image](https://github.com/pokedotdev/tokyo-night-insomnia/assets/40857565/8cb1fff4-8f85-48f2-9708-af5effeb3538)

**Comment by SylvanasCry** [comment]
@pokedotdev It works! Thank you very much, mister :) I also use the Tokyo Night theme in my GoLand IDE from Jetbrains. This theme is wonderful!
